# ==========================================
# DMI Interactiva Frontend & API Reverse Proxy
# ==========================================

# Redirección automática si no se incluye la barra inclinada al final
location = /iaslab/dmi {
    return 301 /iaslab/dmi/$is_args$args;
}

# Frontend React (Puerto 3060)
location /iaslab/dmi/ {
    proxy_pass http://127.0.0.1:3060/iaslab/dmi/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

# Backend NestJS API + WebSockets / Socket.io + Uploads (Puerto 8070)
location /iaslab/dmiapi/ {
    proxy_pass http://127.0.0.1:8070/iaslab/dmiapi/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass_request_headers on;
    proxy_set_header Authorization $http_authorization;
    proxy_pass_header Authorization;
    proxy_connect_timeout 300s;
    proxy_send_timeout 600s;
    proxy_read_timeout 600s;
    send_timeout 600s;
}
